---
title: "Lab 7"
author: "Isaac Plotkin"
date: "3/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
library(pROC)
library(plotROC) 
library(knitr)
```

1.
```{r}
spotify_data <- read_csv("spotify.csv") %>%
  drop_na() %>% #remove observations with missing values
  mutate(key = case_when(
    key == 2 ~ "D", 
    key == 3 ~ "D#", 
    TRUE ~ "Other"
  ),
  target = as.factor(target), 
  )

ggplot(data = spotify_data, aes(x = key, fill = target)) + 
  geom_bar(position = "fill") + 
  labs(y = "target", title = "Target vs Key") +
  coord_flip()
```

2.
```{r}
target_model <- glm(target ~ acousticness + danceability + duration_ms + instrumentalness + loudness +
                speechiness + valence, data = spotify_data, family = binomial)

tidy(target_model, conf.int = TRUE, exponentiate = FALSE)
```

3.
```{r}
target_key_model <- glm(target ~ acousticness + danceability + duration_ms + instrumentalness + 
                        loudness + speechiness + valence + key, 
                        data = spotify_data, family = binomial)

tidy(target_key_model, conf.int = TRUE, exponentiate = FALSE)

anova(target_model, target_key_model, test = "Chisq")
```

4.
```{r}
tidy(target_key_model, conf.int = TRUE, exponentiate = FALSE)

```

keyD# shows that the target score decreases by -1.07% for every song that uses that key.

5. 
```{r}
spotify_aug <- augment(target_key_model, type.predict = "response",
                       type.residuals = "deviance")

spotify_aug
```

6.
```{r}
arm::binnedplot(x = spotify_aug$.fitted, y = spotify_aug$.resid,
                xlab = "Predicted Probabilities", 
                main = "Binned Residual vs. Predicted Values", 
                col.int = FALSE)
```

7. 
```{r}
arm::binnedplot(x = spotify_aug$danceability, y = spotify_aug$.resid,
                xlab = "Danceability", 
                main = "Binned Residual vs. Danceability", 
                col.int = FALSE)
```

8.
```{r}
ggplot(data = spotify_aug, aes(x = key, y = .resid)) + 
  geom_boxplot()
```

9. 
The linearity assumption is not satisfied because the binned residual vs predicted values plot does not have a cloud distribution. It has a V shape pattern to it. I also did not test every variable's residual plot for patterns.

### Part III: Model Assessment & Prediction
10. 
```{r}
(roc_curve <- ggplot(spotify_aug, 
                     aes(d = as.numeric(target) - 1, 
                         m = .fitted)) +
  geom_roc(n.cuts = 10, labelround = 3) + 
  geom_abline(intercept = 0) + 
  labs(x = "False Positive Rate (1 - Specificity)", 
       y = "True Positive Rate (Sensitivity)") )
```




